{
 "title": "NodeJS Metrics",
 "description": "Node Application Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_labels, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_labels{namespace=~\"$namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "namespace" },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "repeat": "namespace",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_microseconds_count{code=~\"^5..$\"}[1m])) /  sum(increase(http_request_duration_microseconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_count[1m])) by (service, route, method, code)  * 60",
     "legendFormat": "{{service}} - {{method}} {{route}} {{code}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "namespace",
   "collapsed": true
  },
  {
   "title": "Median Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "repeat": "namespace",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_microseconds[1m]))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_microseconds_bucket[1m])) by (le, service, route, method))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "95th Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "repeat": "namespace",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_microseconds_bucket[1m])) by (le, service, route, method))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_microseconds_bucket[1m])) by (le, service, route, method))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  }
 ]
}